version: "3.2"
services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    env_file: .env
    volumes:
      - ${BACKREST_LOCAL_DATA}:/data
      - ${BACKREST_LOCAL_CONFIG}:/config
      - ${BACKREST_LOCAL_CACHE}:/cache
      - ${RCLONE_CONFIG}:/root/.config/rclone
      # Backup directories below here. Example:
      - /path:/userdata/path
  
    #  - /MY-REPOS:/repos # [optional] mount repos if using local storage, not necessary for remotes e.g. B2, S3, etc.
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=America/New_York # set the timezone for the container, used as the timezone for cron jobs.
    restart: unless-stopped
    ports:
      - 9898:9898